/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1a1c1e",
        "surface-variant": "#e2e2e2",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#254188",
        "secondary-fixed-dim": "#c6c6c9",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "secondary-fixed": "#e2e2e5",
        "on-secondary-fixed-variant": "#454749",
        "secondary": "#5d5e61",
        "on-primary-fixed": "#241a00",
        "inverse-primary": "#e9c349",
        "on-primary-fixed-variant": "#574500",
        "surface-container": "#eeeeee",
        "surface-container-low": "#f3f3f3",
        "on-tertiary-fixed-variant": "#27438a",
        "tertiary-container": "#97b0ff",
        "surface-tint": "#735c00",
        "on-surface": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "on-secondary": "#ffffff",
        "on-background": "#1a1c1c",
        "on-primary": "#ffffff",
        "outline": "#7f7663",
        "inverse-surface": "#2f3131",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#00174b",
        "secondary-container": "#e2e2e5",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "primary-fixed": "#ffe088",
        "primary-container": "#d4af37",
        "outline-variant": "#d0c5af",
        "on-secondary-container": "#636467",
        "primary-fixed-dim": "#e9c349",
        "inverse-on-surface": "#f1f1f1",
        "error": "#ba1a1a",
        "on-primary-container": "#554300",
        "background": "#f9f9f9",
        "tertiary-fixed": "#dbe1ff",
        "primary": "#735c00",
        "error-container": "#ffdad6",
        "tertiary": "#415ba4",
        "on-surface-variant": "#4d4635",
        "on-error-container": "#93000a",
        "surface": "#f9f9f9"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "IBM Plex Sans Arabic", "sans-serif"],
        "body": ["Inter", "IBM Plex Sans Arabic", "sans-serif"],
        "label": ["Inter", "IBM Plex Sans Arabic", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms')
  ],
}
